# Generated by Django 3.1.6 on 2021-02-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210204_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-time']},
        ),
    ]
